---
- name: AWX export
  hosts: localhost
  connection: local

  tasks:

   - name: Export 
     awx.awx.export:
       job_templates: 'all'
     register: job_templates

   - name: Convert JSON to YAML
      set_fact:
        yaml_data: "{{ job_templates | from_json | to_yaml }}"

  
   - debug: var=yaml_data