---
- name: AWX export
  hosts: localhost
  connection: local
  vars:
    - git_user: davidthong
    - git_pat: "{{ github_pat }}"
    - repo_url: "https://{{ git_user }}:{{ git_pat }}@github.com/{{ git_user }}/awx_import_poc.git"
    - repo_dir: /tmp/export
  vars_files:
    - vault.yml

  tasks:

   - name: Clone the repository if it doesn't exist
     ansible.builtin.git:
      repo: "{{ repo_url }}"
      dest: "{{ repo_dir }}"
      clone: yes
      update: yes
    
   - name: config email
     ansible.builtin.command:
      cmd: "git config --global user.email 'dthong@gmail.com'"
      chdir: "{{ repo_dir }}"
  
   - name: config name
     ansible.builtin.command:
      cmd: "git config --global user.name 'david thong'"
      chdir: "{{ repo_dir }}"

   - name: Export 
     awx.awx.export:
       job_templates: 'all'
     register: job_templates.assets

   - name: Convert JSON to YAML
     ansible.builtin.set_fact:
        yaml_data: "{{ job_templates | to_yaml }}"

   - debug: var=yaml_data

   - debug: var=job_templates

   - name: Template a file to /etc/file.conf
     ansible.builtin.template:
       src: job_templates.j2
       dest: "{{ repo_dir}}/output/job_templates.yml"

   - name: Add the file to the Git repository
     ansible.builtin.command:
      cmd: "git add . "
      chdir: "{{ repo_dir }}"

   - name: Commit the changes
     ansible.builtin.command:
      cmd: git commit -m 'update templates yaml'
      chdir: "{{ repo_dir }}"
     ignore_errors: yes
    
   - name: Push the changes to the remote repository
     ansible.builtin.command:
        cmd: "git push origin main"  # Replace 'main' with your branch name if different
        chdir: "{{ repo_dir }}"