---
- name: AWX export
  hosts: localhost
  connection: local
  vars:
    - repo_url: "https://github.com/davidthong/awx_import_poc.git"
    - repo_dir: /tmp/export

  tasks:

   - name: Clone the repository if it doesn't exist
     ansible.builtin.git:
      repo: "{{ repo_url }}"
      dest: "{{ repo_dir }}"
      clone: yes
      update: yes

   - name: Export 
     awx.awx.export:
       job_templates: 'all'
     register: job_templates

   - name: Convert JSON to YAML
     ansible.builtin.set_fact:
        yaml_data: "{{ job_templates | to_yaml }}"

  
   - debug: var=yaml_data

   - debug: var=job_templates

   - name: Template a file to /etc/file.conf
     ansible.builtin.template:
       src: job_templates.j2
       dest: "{{ repo_dir}}/output/job_templates.yml"

   - name: Add the file to the Git repository
     ansible.builtin.command:
      cmd: "git add . "
      chdir: "{{ repo_dir }}"

   - name: Commit the changes
     ansible.builtin.command:
      cmd: 'git commit -m "update templates yaml'
      chdir: "{{ repo_dir }}"
     ignore_errors: yes
    
   - name: Push the changes to the remote repository
     ansible.builtin.command:
        cmd: "git push origin main"  # Replace 'main' with your branch name if different
        chdir: "{{ repo_dir }}"