- name: Fetch Host Metrics older than 30 days
  hosts: localhost
  gather_facts: false


  tasks:
  
    - name: Calculate date 30 days ago
      ansible.builtin.set_fact:
        date_30_days_ago: "{{ (lookup('ansible.builtin.pipe', 'date -d '30 days ago' +'%Y-%m-%d'')) }}"

    - name: Show the date 30 days ago
      debug:
        msg: "Date 30 days ago: {{ date_30_days_ago }}"
