- name: Fetch Host Metrics older than 30 days
  hosts: localhost
  gather_facts: false


  tasks:
  
    - name: Calculate date 30 days ago
      ansible.builtin.set_fact:
        date_30_days_ago: "{{ (ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ') - timedelta(days=30)).strftime('%Y-%m-%d') }}"

    - name: Show the date 30 days ago
      debug:
        msg: "Date 30 days ago: {{ date_30_days_ago }}"
