---
- name: Get date for 30 days ago
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get current date
      set_fact:
        current_date: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"

    - name: Calculate date 30 days ago
      set_fact:
        date_30_days_ago: "{{ (current_date | to_datetime('%Y-%m-%d') - timedelta(days=30)).strftime('%Y-%m-%d') }}"

    - name: Show the date 30 days ago
      debug:
        msg: "Date 30 days ago: {{ date_30_days_ago }}"
