- name: Get date for 30 days ago
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get current date in YYYY-MM-DD format
      command: date +%Y-%m-%d
      register: current_date

    - debug: var=current_date

    - name: Calculate date 30 days ago
      command: date -d "{{ current_date.stdout }} - 30 days" +%Y-%m-%d
      register: date_30_days_ago

    - name: Show the date 30 days ago
      debug:
        msg: "Date 30 days ago: {{ date_30_days_ago.stdout }}"
