- name: Get date for 30 days ago
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Calculate date 30 days ago
      set_fact:
        date_30_days_ago: "{{ (now() - 30 * 86400) | strftime('%Y-%m-%d') }}"

    - name: Show the date 30 days ago
      debug:
        msg: "Date 30 days ago: {{ date_30_days_ago }}"
