- name: PR playbook  
  hosts: localhost
  connection: local 
  vars:
     githubUrl: "api.github.com"
     githubOrgName: davidthong
     github_repo_name: awx_import_poc
     sourceBranch: dev
     targetBranch: main

  tasks:  
    
    - name: Handle createPullRequest errors
      block:
        - debug:
            msg:
              - "### Input variable passed to role ###"
              - "githubUrl - {{ githubUrl }}"
              - "githubOrgName - {{ githubOrgName }}"
              - "Github Repo Name - {{ github_repo_name }}"
              - "sourceBranch - {{sourceBranch}}"
              - "targetBranch - {{targetBranch}}"

    - name: Set variable
      set_fact:
        sourceBranch: "{{ sourceBranch }}"
        targetBranch: "{{ targetBranch }}"
        github_repo_name: "{{ github_repo_name }}"

    - name: Create summary list for appending messages to
      set_fact:
        summary_list: ""
      when: summary_list is not defined

    - name: Cigna github.com block
      block:
        - name: Create PR request in Github.com project {{ github_repo_name }}
          uri:
            url: "{{ githubUrl }}/repos/{{ githubOrgName }}/{{ github_repo_name }}/pulls"
            body: "{{ lookup('template', 'pr-request.json') }}"
            force_basic_auth: yes
            user: "{{ githubUser }}"
            password: "{{ githubToken }}"
            body_format: json
            method: POST
            validate_certs: no
            status_code: 200,201,203,422
            headers:
              Accept: application/vnd.github.v3+json
          register: github_pr_status

        - debug: var=github_pr_status

        - name: Debug Status code for PR
          debug:
            msg: PR already exists or No commits between {{targetBranch}} and {{sourceBranch}}
          when: github_pr_status.status == 422
      when: github_endpoint | regex_search('github.com')


    - name: Cigna github block
      block:
        - name: Create PR request in Github project {{ github_repo_name }}
          uri:
            url: "{{ githubUrl }}/api/v3/repos/{{ githubOrgName }}/{{ github_repo_name }}/pulls"
            body: "{{ lookup('template', 'pr-request.json') }}"
            force_basic_auth: yes
            user: "{{ githubUser }}"
            password: "{{ githubToken }}"
            body_format: json
            method: POST
            validate_certs: no
            status_code: 200,201,203,422
            headers:
              Accept: application/vnd.github.v3+json
          register: github_pr_status

        - name: Debug Status code for PR
          debug:
            msg: PR already exists or No commits between {{targetBranch}} and {{sourceBranch}}
          when: github_pr_status.status == 422
      when: github_endpoint | regex_search('github.sys.cigna.com')

 
    - name: ESI github block
      block:
        - name: Create PR request in Github project {{ github_repo_name }}
          uri:
            url: "{{ githubUrl }}/api/v3/repos/{{ githubOrgName }}/{{ github_repo_name }}/pulls"
            body: "{{ lookup('template', 'pr-request.json') }}"
            force_basic_auth: yes
            user: "{{ githubUser }}"
            password: "{{ githubTokenESI }}"
            body_format: json
            method: POST
            validate_certs: no
            status_code: 200,201,203,422
            headers:
              Accept: application/vnd.github.v3+json
          register: github_pr_status

        - name: Debug Status code for PR
          debug:
            msg: PR already exists or No commits between {{targetBranch}} and {{sourceBranch}}
          when: github_pr_status.status == 422
        
        - name: Update summary list with success message
          set_fact:
            summary_list: '{{ summary_list }};"{{ role_name }} ,"successful"'

        - name: Add Team Reviewers to The PR
          ansible.builtin.uri:
            url: "{{ githubUrl }}/api/v3/repos/{{ githubOrgName }}/{{ github_repo_name }}/pulls"
            body: "{{ lookup('template', 'pr-request.json') }}"
            force_basic_auth: yes
            user: "{{ githubUser }}"
            password: "{{ githubTokenESI }}"
            body_format: json
            method: POST
            validate_certs: no
            status_code: 200,201,203,422
            headers:
              Accept: application/vnd.github.v3+json
          register: github_pr_status
          when: github_reviewers is defined and github_reviewers | length > 0
          
      when: github_endpoint | regex_search('git.express-scripts.com')   

      rescue:
        - name: Update summary list with failure message
          set_fact:
            summary_list: '{{ summary_list }};"{{ role_name }} ,"failed"'
            fail_main_playbook: true
        - name: Failing createPullRequest
          fail:
            msg: '{{ ansible_failed_result }}'